### ISSUE TITLE
ex06_multipleObjects Fails

### ISSUE THREAD

**Issue by kyamant** [ingowald/optix7course#22] opened 2021-08-03 19:55 UTC
#osc: initializing optix...
#osc: found 1 CUDA devices
#osc: successfully initialized optix... yay!
#osc: creating optix context ...
#osc: running on device: NVIDIA GeForce GTX 1050 Ti
#osc: setting up module ...
[ 4][   DISKCACHE]: Cache miss for key: ptx-6226-key6b12d97c881e14b42b73d87f92188994-sm_61-rtc0-drv471.11
[ 4][COMPILE FEEDBACK]: Info: Pipeline parameter "optixLaunchParams" size is 72 bytes

[ 4][   DISKCACHE]: Inserted module in cache with key: ptx-6226-key6b12d97c881e14b42b73d87f92188994-sm_61-rtc0-drv471.11
[ 4][COMPILE FEEDBACK]: Info: Module uses 2 payload values.Info: Module uses 0 attribute values. Pipeline configuration: 2 (default).
Info: Entry function "__closesthit__radiance" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 108 instruction(s)
Info: Entry function "__anyhit__radiance" with semantic type ANYHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 1 instruction(s)
Info: Entry function "__miss__radiance" with semantic type MISS has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 14 instruction(s)
Info: Entry function "__raygen__renderFrame" with semantic type RAYGEN has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 92 instruction(s)
Info: 0 non-entry function(s) have 0 basic block(s), 0 instruction(s)

log=Info: Pipeline parameter "optixLaunchParams" size is 72 bytes
Info: Module uses 2 payload values.Info: Module uses 0 attribute values. Pipeline configuration: 2 (default).
Info: Entry function "__closesthit__radiance" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 108 instruction(s)
Info: Entry function "__anyhit__radiance" with semantic type ANYHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 1 instruction(s)
Info: Entry function "__miss__radiance" with semantic type MISS has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 14 instruction(s)
Info: Entry function "__raygen__renderFrame" with semantic type RAYGEN has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 1 basic block(s), 92 instruction(s)
Info: 0 non-entry function(s) have 0 basic block(s), 0 instruction(s)

#osc: creating raygen programs ...
#osc: creating miss programs ...
#osc: creating hitgroup programs ...
[ 2][       ERROR]: "buildInputs[1].type" != "buildInputs[0].type". All build inputs for geometry acceleration structures must have the same type
Optix call (optixAccelComputeMemoryUsage( optixContext, &accelOptions, triangleInput.data(), (int)meshes.size(), &blasBufferSizes)) failed with code 7001 (line 165)

**Comment by ingowald** [comment] 2021-08-03 22:19
Thx for reporting this.
It's actually interesting in that this apparently only happens in Optix 7.3 (not 7.2 or 7.1, I just tested), but there's no reason that those two versions should behave differently. I'll look into it.

**Comment by ingowald** [comment] 2021-08-03 22:22
Wait, I had the wrong driver, that's why 7.3 didn't work. 
Can you tell me with version of OptiX and CUDA you're using, and which OS? The two build inputs _are_ actually the same, so somewhat confused why you're seeing this.

**Comment by ingowald** [comment] 2021-08-03 22:36
Hm. Just updated driver, and can't reproduce this - tested 7.1, 7.2, and 7.3, in both debug and release mode; they all work.
Can you provide driver version, cuda version, optix version, and OS?

**Comment by ingowald** [comment] 2021-08-03 22:56
Also just tried windows - same: works on my side.

**Comment by kyamant** [comment] 2021-08-04 06:36
Display driver 471.41
OptiX 7.2
CUDA 11.4
Tried debug mode only under: Microsoft Visual Studio Enterprise 2019 Version 16.10.4

**Comment by kyamant** [comment] 2021-08-04 06:42
Same with Release mode

**Comment by ingowald** [comment] 2021-08-04 20:15
Hm. I have OptiX 7.3 on my windows machine - not 7.2 - but after some installing and reinstalling all other items I now match exactly - same driver, same cuda, same VS version .... but can't reproduce. Biggest difference I could see right now is your GPU - I have a 2070 in my windows box, you have a 1050TI .... but I couldn't possibly see how that could make a difference.

I'll see if I can find anything that's closer to that 1070 - I think i have some 1070s left in the basement.

**Comment by ingowald** [comment] 2021-08-04 20:29
Also just tested with a 1070; same result: works just fine on my side in both release and devel - save driver, same cuda, same VS.

Are you sure you're running exactly the same version of the code off github that I'm using? you don't have any local changes in your codebase, even any made to other samples that might have unexpected side effects on the ex06 one?

What I can't understand is that your outputs very clearly describe what the issue is supposed to be - namely a differnet type in the two build inputs - but there's literally only two build inputs, they're set right before the failing function, and to definitely the same value, all in host code that wouldn't even depend on cuda, driver, gpu type, etcpp.

**Comment by ingowald** [comment] 2021-12-29 20:41
Cannot reproduce - closing this

**Closed as completed by ingowald** 2021-12-29 20:41 UTC
